drawshield/Drawshield-Code

svg/svgtools.inc

svg/charges/emblem/star-of-david.svg includes a <path> element with id="t". This
short ID caused an "Uninitialized string offset" notice for the expression
$id[$len-2]. (The notice is perhaps easy to miss; it is printed to stderr and
should show up in server error logs.)
Tested:
Before:
$ php drawshield.php 'Argent, a star of David azure'
PHP Notice:  Uninitialized string offset: -1 in /home/brian/repos/Drawshield-Code/svg/svgtools.inc on line 180
<?xml version="1.0" encoding="utf-8" ?>
...
After:
$ php drawshield.php 'Argent, a star of David azure'
<?xml version="1.0" encoding="utf-8" ?>
...

Fix "uninitialized string offset".

---

svg/charges/geometric/bezant.inc

The user guide indicates that a bezant is simply a roundel, like a golpe, guze,
hurt, and so on. This matches other sources, which describe a bezant as a
roundel or. So it is surprising if "bezant" is different from "roundel or". Most
illustrations including bezants also show them as flat discs, not as
three-dimensional representations of coins in perspective.
Tested:
$ php drawshield.php 'Azure, three bezants' | convert - out.png

Change bezant to look like other roundels.

---

svg/charges/alchemical/symbol.inc
svg/charges/astronomical/symbol.inc
svg/charges/characters/letter.inc
svg/charges/symbol/any.inc
svg/charges/zodiac/symbol.inc

For alchemical, astronomical, and zodiac symbols, and names of fonts, a token from the blazon is used as a file name. This doesn't work if the token is capitalised, because the file names are lower-case. Case-insensitivity is especially important for astronomical and zodiac symbols, because the names there (e.g., Saturn, Capricorn) are properly written with an initial capital letter.
Before: WARNING No symbol for Air (using fire)
After:
Before: WARNING No symbol for Venus (using sun)
After:
Before (note that this is the Gothic font):
After:
Before: WARNING No symbol for Water (using fire)
After:
Before: WARNING No symbol for Jupiter (using fire)
After:
Before: WARNING No symbol for Leo (using aries)
After:

Case-insensitivity for symbols.

---

svg/charges/symbol/any.inc

This allows zodiac symbols to be referenced without the word "zodiac", like alchemical and astronomical symbols already can.
Tested:
Argent, a symbol for pisces sable
Before: WARNING No symbol for pisces (using fire)
After:

Support zodiac symbols via symbol/any.

---

svg/tinctures.inc

Because of a typo, the previous code tried to put a bunch of SVG into a `width` attribute.
Test blazon: Argent, a chevron inverted chequy azure and or.

Fix treatments on inverted objects.

---

svg/tinctures.inc

The previous code attempted to access an array element by numeric index, when it's actually an associative array. This caused a warning from PHP and a malformed `translate` transform in the SVG.
Test blazon: Argent, a chevron inverted pean.
Before: The expression `$fur_data[1]` caused the following notice from PHP:
PHP Notice:  Undefined offset: 1 in /home/brian/repos/Drawshield-Code/svg/tinctures.inc on line 179
And the output SVG contained the following:
<g transform="translate(0,) scale(1,-1)">
Note the malformed `translate` here. The result was that either the ermine spots were upside-down or the fur was not drawn at all, depending on the SVG renderer. Example:
After: The shield is drawn correctly, with the ermine spots upright.

Fix furs on inverted objects.

---

parser/english/charge.inc

The visual catalog (https://drawshield.net/catalog/charges/human/index.html) lists "monk" as a charge, and the SVG exists; it was just missing from the parser.
As a resident of Munich, it is personally important to me to support blazons that include monks.
Test blazon: Argent, a monk sable.

Add "monk" to the parser.

---

parser/english/lexicon.inc

Commit ef284f78582d16f8d89aef17a363443f19d733c5 fixed the handling of apostrophes in phrases such as "horse's head". Unfortunately it broke the handling of these tinctures for gouttes.
Test blazons:
Sable, three gouttes d'or.
Sable, three gouttes d'eau.
Argent, three gouttes d'huile.
Argent, three gouttes d'olive.

Fix "d'or", "d'eau", "d'huile", and "d'olive".

---

parser/english/charge.inc

This change adds support for the phrasing "Saint Florian's cross" and fixes the charge.
Test blazons:
Argent, a Saint Florian cross gules.
Argent, a Saint Florian's cross gules.

Tweaks to "Saint Florian cross".

---

parser/english/charge.inc

The previous regex accepted the spellings "Hanage", "Haneage", "Heanage", and "Heaneage", but not the correct spelling "Heneage". Google returns no results for the quoted phrases "hanage knot" and "haneage knot", so it seems likely that the original intent was to support the spellings "Heanage", "Heaneage", "Henage", and "Heneage".
Test blazon: Argent, a Heneage knot sable.

Fix Heneage knot.

---

svg/charges/dragon/chinese-dragon.inc
svg/charges/serpent/serpent.inc

Following commit 3be81f7c23b5277d1c305e4d6d53f91aa61797e2, which fixed "dragon in annulo", this change takes the same approach to fix these two charges.
Test blazons:
Argent, a Chinese dragon in annulo gules.
Argent, a serpent in annulo vert.

Fix "Chinese dragon in annulo" and "serpent in annulo".

---

svg/ordinaries/fess.inc

These were backward, couped on the wrong side.
Test blazons:
Argent, a fess couped dexter azure.
Argent, a fess couped sinister azure.
Argent, a dance couped dexter azure.
Argent, a dance couped sinister azure.

Fix "{fess,dance} couped {dexter,sinister}".

---

svg/charges/natural/forest.svg

Previously the fill in the SVG was not one of the magic colours, so it was not replaced by the tincture in the blazon.
Test blazon: Argent, a hurst azure.

Fix colouring of "hurst".

---

svg/charges/fish/carp-embowed.svg
svg/charges/fish/catfish-embowed.svg

These charges previously had the "haurient" built into the SVG. But haurient is implemented in general by rotating the charge, so the end result was that these fish were lying on their backs.
This change rotates the SVG images 90 degrees counterclockwise and removes "haurient" from the file names.
Test blazons:
Or, a carp haurient embowed sable.
Or, a catfish haurient embowed sable.

Fix "{carp,catfish} haurient embowed".

---

svg/getcharge.inc
svg/tinctures.inc

I was playing with Drawshield code, I noticed that in order to use it from external scripts some paths need to be updated.
this does that by using __dir__ to form relative paths.

Fix some hard-coded paths

---

svg/arrangements.inc

Looks like "in annulo" doesn't work too well with flags. This fixes it.
Here are some example for "azure 12 mullets of 5 stars or in annulo"
Old behaviour:
Fixed:
Also works for any flag aspect ratio, here's another example:

Take into account the flag height for inAnnulo

---

svg/tinctures.inc

Found a better way of handling palette paths, with my previous change it wouldn't error but always default to 'drawshield' if drawshield-code is in a subdirectory

Update paths for palette files

---

demopage.php
drawshield.php
shieldcommon.js
svg/tinctures.inc

This adds the ability to customize specific colors in the palette
by code:
```php
$options["customPalette"] = [
"heraldic/azure" => "#0000ff",
"heraldic/or" => "#ffff00"
];
```
request to drawshield.php:
```
&customPalette[heraldic%2Fazure]=%230000ff&customPalette[heraldic%2For]=%23ffff00
```
I've also simplified drawshield.php, so we don't need to handle each parameter separately for $_POST and $_GET since they are all handled the same way.

Support for customizing the palette

---

docs/fess-plain.png:Zone.Identifier

Delete an alternate data stream created when a file was downloaded from the internet and committed as a separate file with an on-Windows-unrepresentable filename, causing the repository to be un-checkout-able on Windows.

Delete zone identifier alternate data stream

---

utils/render.inc

Without this calling drawshield.php to render an image can give errors:
```
Error: Expected positive integer for height but received 614.4 of type number
at Object.invalidParameterError (/opt/bitnami/var/img-server/node_modules/sharp/lib/is.js:135:10)
at Sharp.resize (/opt/bitnami/var/img-server/node_modules/sharp/lib/resize.js:268:16)
at /opt/bitnami/var/img-server/img-server.js:68:10
at Layer.handle [as handle_request] (/opt/bitnami/var/img-server/node_modules/express/lib/router/layer.js:95:5)
at next (/opt/bitnami/var/img-server/node_modules/express/lib/router/route.js:144:13)
at done (/opt/bitnami/var/img-server/node_modules/multer/lib/make-middleware.js:45:7)
at indicateDone (/opt/bitnami/var/img-server/node_modules/multer/lib/make-middleware.js:49:68)
at Multipart.<anonymous> …
```

Ensure when rendered as file, image size is an integer.

---

svg/ordinaries/bar.inc

The y position of the bar was slightly off (`$H2` wasn't being updated together with `$H1`)

Fix bar position

---

drawshield.php
parser/english/lexicon.inc

Just a couple small fixes:
In newer PHP versions strings `\x12` seem to be parsed by the regex engine so it needs to be double escaped. Not sure how this behaves in older versions so it might need to be tested before merging. (Without this fix `$options['blazon']` is set to an empty string).
The English lexicon change allows for drawshield code being accessed from a different directory (i.e.: Using drawshield as a library)

Small fixes
